### PR TITLE
Rafale77 patch 1

### PR DESCRIPTION
**Pull request by rafale77**
Updated to 1.7 with UI7 mods and Ecobee3 housemodes

### CODE REVIEW

**Comment by rafale77** [comment]
UI7 version

**Comment by watou** [comment]
Thank you very much for this!  

What are your thoughts about the subject of UI5 compatibility?  If I submit this PR to apps.mios.com, can you field any support issues that might arise?  I very much want to share your work, but won't have time to sort out any issues.  In any case, your PR is much appreciated.  Just let me know if you think it's good to go in the current state.  Regards, John

**Comment by rafale77** [comment]
Yes I can support issues. The changes were quite minor, mostly graphical. The biggest change is on the housemode in which I incorporated the 3rd default mode on the ecobee3 and a 4th mode to match the Vera UI7 modes.

I would have to see how to direct to different device json depending on the UI. This has been done before. I can probably just use the same method. I just happen to see people on the forum asking for house mode syncing and wanted to share what I did.

**Comment by watou** [comment]
Great!  Thanks for that.  I will try to submit this PR as is to apps.mios.com this evening, and report back here when it's submitted.  I don't know how long the approval process is these days.

I'm also going to remove the Donate button from the doc page, since I would prefer this becomes a "community-owned" plugin going forward.

**Comment by watou** [comment]
I've just submitted this to apps.mios.com!  Thanks again.

**Comment by watou** [comment]
Hi @rafale77, it looks like v1.7 was approved on Monday 20 March, so people should be upgrading to it starting then.

**Comment by rafale77** [comment]
Yes, Thank you. I already got some feedback on the forum.

**Pull request merged**
